package com.example.suppy.home.chatlist

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.models.chat.DomainChat
import com.example.models.chat.EntityChat
import com.example.models.message.EntityMessage
import com.example.repository.ChatRepo
import com.example.repository.MessageRepo
import com.example.repository.webservicemodule.Server
import com.example.suppy.util.VoidEvent
import com.example.suppy.move_out.SomeDataModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.jivesoftware.smack.chat2.Chat
import org.jivesoftware.smack.chat2.ChatManager
import timber.log.Timber
import java.util.*
import kotlin.collections.ArrayList

/**
 * NOTE use [AndroidViewModel] only if your view model requires context
 */
class ChatsViewModel : ViewModel() {
    lateinit var bundle: DomainChat
    lateinit var chatMan: ChatManager
    lateinit var chat: Chat
    /**
     * Used to store randomly generated chat records
     * to be used to remove those records again on
     * button click to test recyclerview reaction
     * to database record deletion
     * TODO temp
     */
    private var addedRecords: ArrayList<EntityChat> = arrayListOf()

    /**
     * Standard UI navigation code
     * TODO replace the get with a delegation if possible
     */
    private val _navigateToChatMessages = MutableLiveData<VoidEvent>()
    val navigateToChatMessages: LiveData<VoidEvent>
        get() = _navigateToChatMessages
    fun navigate() {
        _navigateToChatMessages.value = VoidEvent()
        Timber.d("Chat clicked from VM: $bundle")
    }

    /**
     * Start server connection
     */
    fun startServerConnection() {
        viewModelScope.launch(Dispatchers.IO) {
            Server.instance()
        }
    }

    /**
     * Return all chats from database wrapped
     * in LiveData
     * TODO temp
     */
    fun getAllChatLocalData(): LiveData<List<EntityChat>> {
        Timber.d("Returning chat live data from VM (calling repo)")
        return ChatRepo().chats()
    }

    /**
     * Return all messages from database wrapped
     * in LiveData
     * TODO temp
     */
    fun getLatestMessaageLocalData(): LiveData<EntityMessage> {
        Timber.d("Returning latest message live data from VM (calling repo)")
        return MessageRepo().latestMessage()
    }

    /**
     * Display the amount of randomly generated chats
     * that is suppose to exist in the database
     * TODO temp
     */
    private fun randomRecordsCount() {
        Timber.d("RANDOM RECORDS COUNT: ${addedRecords.size}")
    }

    /**
     * Fetch all chats from databse to be
     * displayed to confirm autogenerated
     * ID field
     * TODO temp
     */
    fun localRecords() {
        randomRecordsCount()
        Timber.d("Viewmodel wants to fetch all the chats from local storage...")
        viewModelScope.launch(Dispatchers.IO) {
            val data = ChatRepo().justChats()
            Timber.d("Local chats from database:")
            data.forEach {
                Timber.d("[id=${it.id}, name=${it.chatName}]")
            }
        }
    }

    /**
     * Delete a record in local storage from an
     * arraylist of randomly generated records
     * that have been entered into local storage
     * TODO temp
     */
    fun deleteRecord() {
        val random = Random().nextInt(addedRecords.size)
        Timber.d("Random int: $random")
        val toBeRemoved = addedRecords.get(random)
        addedRecords.remove(toBeRemoved)
        randomRecordsCount()
        viewModelScope.launch {
            withContext(Dispatchers.IO) {
                ChatRepo().deleteRow(toBeRemoved.chatName)
            }
        }
    }

    /**
     * Create a chat entity to be added to local
     * database to confirm recyclerview data is
     * updated when data changes
     * TODO temp
     */
    fun insertRandomChat() {
        val s = EntityChat(
            chatName = "Person ${Random().nextInt(9999)}",
            lastActivity = "las",
            mute = false,
            description = "def desc",
            creator = "cre",
            createdAt = "cred at",
            subType = "subty",
            bareJid = "jidd",
            approved = true,
            subPending = false,
            commonGroups = "no groups yo"
        )
        addedRecords.add(s) // saved to reference when wanting to delete a list item
        randomRecordsCount()
        Timber.d("insert this: $s")
        viewModelScope.launch (Dispatchers.IO){
            ChatRepo().insert(
                s
            )
        }
    }

    /**
     * Build and send a message stanza
     * TODO temp
     */
    fun sendMsgStanza(content: String, to: String) {
//        val msgStanza = Message(
//            JidCreate.bareFrom("${to}@jabber-hosting.de"),
//            "$content"
//        )
//        msgStanza.type = Message.Type.chat
//        Server.instance().sendStanza(msgStanza)
//        if(!::chat.isInitialized) {
//            if(!::chatMan.isInitialized) {
//                chatMan = ChatManager.getInstanceFor(Server.instance())
//                chatMan.addIncomingListener(ConnectionListener())
//            }
//            chat = chatMan.chatWith(JidCreate.entityBareFrom("${to}@jabber-hosting.de"))
//        }
//        chat.send("$content")
    }

    /**
     * Dummy data
     *
     * TODO Replace with real data :)
     */
    val data = arrayListOf(
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        ),
        SomeDataModel(
            "Chat with ${Random().nextInt(
                9999
            )}", "Description ${Random().nextInt(9999)}"
        )
    )
}